'use client';
import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { registerColoringTools } from '@/lib/webmcp';
import { Palette, Undo2, Eraser, RotateCcw, Download, Check, Heart, Sparkles, Volume2, VolumeX, ChevronRight, X, MousePointer2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { findRegions, paintRegions, type Segmentation } from '@/lib/coloring';
const pictures = [
 { name:'ผีเสื้อแสนสวย',short:'ผีเสื้อ',category:'สัตว์น่ารัก',position:'0% 0%',tint:'#f2edff' },
 { name:'ดอกไม้ยิ้มแฉ่ง',short:'ดอกไม้',category:'ธรรมชาติ',position:'100% 0%',tint:'#fff2dc' },
 { name:'บ้านแสนอบอุ่น',short:'บ้าน',category:'รอบตัวเรา',position:'0% 100%',tint:'#fce9e5' },
 { name:'วาฬน้อยใจดี',short:'วาฬน้อย',category:'สัตว์น่ารัก',position:'100% 100%',tint:'#e7f3fb' },
];
const colors = [['#F47777','แดง'],['#FFAD66','ส้ม'],['#F9D85B','เหลือง'],['#8BCA8C','เขียว'],['#66C8C1','เขียวมิ้นต์'],['#7EBBEE','ฟ้า'],['#8790DE','น้ำเงิน'],['#B99ADE','ม่วง'],['#F0A3C6','ชมพู'],['#B88E77','น้ำตาล'],['#596078','เทา'],['#FFFFFF','ขาว']];
type Work={fills:Record<number,string>;history:Record<number,string>[]};
const SIZE=640;
export default function Home(){
 const [picture,setPicture]=useState(0),[color,setColor]=useState(colors[0][0]),[erasing,setErasing]=useState(false);
 const [works,setWorks]=useState<Work[]>(pictures.map(()=>({fills:{},history:[]})));
 const [ready,setReady]=useState(false),[error,setError]=useState(false),[regions,setRegions]=useState<Segmentation|null>(null);
 const [sound,setSound]=useState(false),[notice,setNotice]=useState('เลือกสีที่ชอบ แล้วแตะในรูปได้เลย');
 const [help,setHelp]=useState(false),[resetOpen,setResetOpen]=useState(false),[keyboardRegion,setKeyboardRegion]=useState(-1);
 const canvas=useRef<HTMLCanvasElement>(null),audio=useRef<AudioContext|null>(null);
 const current=works[picture],total=regions?.regions.length??0,completed=regions?Object.keys(current.fills).filter(k=>Number(k)<total).length:0;
 const bridge=useRef({read:()=>({picture,total,fills:current.fills,colors:colors.map(c=>c[0])}),fill:(id:number,hex:string)=>fill(id,hex,false)});
 bridge.current={read:()=>({picture,total,fills:current.fills,colors:colors.map(c=>c[0])}),fill:(id,hex)=>fill(id,hex,false)};
 useEffect(()=>registerColoringTools(()=>bridge.current.read(),(id,hex)=>flushSync(()=>bridge.current.fill(id,hex))),[]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('taemsee-works-v1')||'null');if(Array.isArray(saved)&&saved.length===4)setWorks(saved.map(f=>({fills:Object.fromEntries(Object.entries(f||{}).filter(([k,v])=>/^\d+$/.test(k)&&typeof v==='string'&&/^#[0-9a-f]{6}$/i.test(v))) as Record<number,string>,history:[]})));}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('taemsee-works-v1',JSON.stringify(works.map(w=>w.fills)));}catch{}},[works,ready]);
 useEffect(()=>{let active=true;setRegions(null);setError(false);setKeyboardRegion(-1);const img=new Image();img.src='/coloring-sheet.png';img.onload=()=>{if(!active)return;const c=document.createElement('canvas');c.width=SIZE;c.height=SIZE;const ctx=c.getContext('2d',{willReadFrequently:true})!;ctx.fillStyle='#fff';ctx.fillRect(0,0,SIZE,SIZE);const sh=img.height*(picture===1?.515:.5);ctx.drawImage(img,(picture%2)*img.width/2,Math.floor(picture/2)*img.height/2,img.width/2,sh,28,28,SIZE-56,SIZE-56);setRegions(findRegions(ctx.getImageData(0,0,SIZE,SIZE)));};img.onerror=()=>{if(active)setError(true);};return()=>{active=false;};},[picture]);
 useEffect(()=>{if(!regions||!canvas.current)return;const ctx=canvas.current.getContext('2d')!;ctx.putImageData(new ImageData(paintRegions(regions,current.fills),SIZE,SIZE),0,0);if(keyboardRegion>=0&&regions.regions[keyboardRegion]){const r=regions.regions[keyboardRegion];ctx.strokeStyle='#7760b4';ctx.lineWidth=3;ctx.setLineDash([6,6]);ctx.strokeRect(r.minX-4,r.minY-4,r.maxX-r.minX+8,r.maxY-r.minY+8);}},[regions,current.fills,keyboardRegion]);
 function fill(region:number,chosen=color,erase=erasing){if(!regions||region<0||region>=total)return;if((erase&&!current.fills[region])||(!erase&&current.fills[region]===chosen))return;setWorks(all=>all.map((w,i)=>{if(i!==picture)return w;const fills={...w.fills};if(erase)delete fills[region];else fills[region]=chosen;return{fills,history:[...w.history.slice(-29),w.fills]};}));setNotice(erase?'ลบสีแล้ว ลองสีใหม่ได้เลย':'สวยจัง! เติมจินตนาการต่อได้เลย');if(sound)try{audio.current??=new AudioContext();void audio.current.resume();const ctx=audio.current,osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=480+region*30;gain.gain.setValueAtTime(.065,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18);osc.start();osc.stop(ctx.currentTime+.18);}catch{}}
 function undo(){setWorks(all=>all.map((w,i)=>i===picture&&w.history.length?{fills:w.history.at(-1)!,history:w.history.slice(0,-1)}:w));setNotice('ย้อนกลับให้แล้ว ลองใหม่ได้เสมอ');}
 function reset(){setWorks(all=>all.map((w,i)=>i===picture?{fills:{},history:[...w.history.slice(-29),w.fills]}:w));setResetOpen(false);setNotice('กระดาษพร้อมแล้ว มาเติมสีใหม่กัน');}
 function download(){if(!regions)return;const c=document.createElement('canvas');c.width=SIZE;c.height=SIZE;c.getContext('2d')!.putImageData(new ImageData(paintRegions(regions,current.fills),SIZE,SIZE),0,0);c.toBlob(blob=>{if(!blob){setNotice('บันทึกไม่สำเร็จ ลองอีกครั้งนะ');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`แต้มสี-${pictures[picture].short}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);setNotice('ดาวน์โหลดรูปแล้ว เก่งมากเลย!');});}
 return <div className="app-shell">
 <header className="topbar"><a className="brand" href="/" aria-label="แต้มสี หน้าหลัก"><span className="brand-icon"><Palette size={27}/></span><span>แต้ม<span className="brand-color">สี</span><small>โลกใบเล็ก สีสันใบใหญ่</small></span></a><nav><span className="nav-active"><Palette size={18}/> ห้องเติมสี</span><Button variant="ghost" className="help-button" onClick={()=>setHelp(true)}>วิธีเล่น</Button></nav><span className="made-for"><Heart size={16}/> พื้นที่เล็ก ๆ ของจินตนาการ</span></header>
 <main><div className="welcome"><div><div className="eyebrow">LET’S MAKE SOMETHING COLORFUL</div><h1>วันนี้… มาแต้มสีอะไรดี? <Sparkles className="heading-sparkle"/></h1><p>แค่เลือกสี แล้วแตะในรูป ก็สร้างผลงานชิ้นเอกได้แล้ว</p></div><Button variant="outline" className="sound-button" onClick={()=>setSound(!sound)} aria-pressed={sound}>{sound?<Volume2/>:<VolumeX/>}<span>เสียง{sound?'เปิด':'ปิด'}</span></Button></div>
 <div className="studio"><aside className="picture-panel"><div className="section-label"><span className="step">1</span><h2>เลือกรูปที่ชอบ</h2></div><div className="picture-list">{pictures.map((p,i)=><Button variant="ghost" key={p.name} className={`picture-card ${picture===i?'selected':''}`} aria-pressed={picture===i} onClick={()=>{setPicture(i);setNotice('เลือกสีที่ชอบ แล้วแตะในรูปได้เลย');}}><span className="picture-thumbnail" style={{backgroundColor:p.tint}}><span style={{backgroundPosition:p.position}}/></span><span className="picture-caption"><strong>{p.short}</strong><small>{p.category}</small></span>{picture===i&&<span className="picture-check"><Check size={12}/></span>}</Button>)}</div><div className="little-note"><Heart size={22}/><p>ไม่มีสีที่ผิด<br/><strong>มีแต่สีที่หนูชอบ</strong></p></div></aside>
 <section className="art-panel" aria-label="พื้นที่เติมสี"><div className="art-header"><div><span className="small-label">ผลงานของศิลปินตัวน้อย</span><h2>{pictures[picture].name}</h2></div><span className="art-count">{picture+1} <span>/ 4</span></span></div><div className="canvas-wrap"><canvas ref={canvas} width={SIZE} height={SIZE} tabIndex={0} aria-label="รูปสำหรับเติมสี ใช้ลูกศรเลือกช่อง แล้วกด Enter หรือ Space เพื่อเติมสี" onPointerDown={e=>{if(!regions)return;const rect=e.currentTarget.getBoundingClientRect(),x=Math.max(0,Math.min(SIZE-1,Math.floor((e.clientX-rect.left)*SIZE/rect.width))),y=Math.max(0,Math.min(SIZE-1,Math.floor((e.clientY-rect.top)*SIZE/rect.height)));setKeyboardRegion(-1);const id=regions.labels[y*SIZE+x];if(id<0)setNotice('ลองแตะในช่องว่างด้านในรูปนะ');else fill(id);}} onKeyDown={e=>{if(!total)return;if(['ArrowRight','ArrowDown','ArrowLeft','ArrowUp'].includes(e.key)){e.preventDefault();setKeyboardRegion(k=>(k+(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1)+total)%total);}if(e.key==='Enter'||e.key===' '){e.preventDefault();if(keyboardRegion<0)setKeyboardRegion(0);else fill(keyboardRegion);}}}/>{!regions&&<div className="canvas-status">{error?<><p>โหลดรูปไม่สำเร็จ</p><Button onClick={()=>window.location.reload()}>ลองอีกครั้ง</Button></>:'กำลังเตรียมรูปน่ารัก ๆ…'}</div>}</div><div className="art-toolbar"><div className="tool-buttons"><Button variant="ghost" onClick={undo} disabled={!current.history.length}><Undo2/> ย้อนกลับ</Button><Button variant="ghost" className={erasing?'tool-active':''} onClick={()=>setErasing(!erasing)} aria-pressed={erasing}><Eraser/> ยางลบ</Button><Button variant="ghost" onClick={()=>setResetOpen(true)} disabled={!completed}><RotateCcw/> เริ่มใหม่</Button></div><span className="canvas-hint"><MousePointer2 size={14}/> แตะแล้วสีมาเลย!</span></div></section>
 <aside className="palette-panel"><div className="section-label"><span className="step mint">2</span><h2>เลือกสีแสนสนุก</h2></div><p className="palette-subtitle">วันนี้หนูชอบสีอะไร?</p><div className="color-grid">{colors.map(([hex,name])=><Button key={hex} className={`swatch ${color===hex&&!erasing?'chosen':''}`} style={{backgroundColor:hex}} onClick={()=>{setColor(hex);setErasing(false);setNotice(`เลือกสี${name}แล้ว แตะในรูปได้เลย`);}} aria-label={`สี${name}`} aria-pressed={color===hex&&!erasing}>{color===hex&&!erasing&&<Check style={{color:hex==='#FFFFFF'?'#615374':'#fff'}}/>}</Button>)}</div><div className="selected-color"><span style={{background:erasing?'#fff':color}}>{erasing&&<Eraser size={18}/>}</span><div><small>กำลังใช้</small><strong>{erasing?'ยางลบ':`สี${colors.find(c=>c[0]===color)?.[1]}`}</strong></div><Check size={16}/></div><div className="palette-divider"/><div className="progress-copy"><span>เติมความสดใสไปแล้ว</span><strong>{completed}<small> / {total} ช่อง</small></strong></div><div className="progress-track"><div style={{width:`${total?completed/total*100:0}%`}}/></div><p className="encouragement">{completed===total&&total>0?'เย้! เติมสีครบแล้ว เก่งมากเลย 🎉':'ค่อย ๆ เติม ตามใจหนูเลย'}</p><Button className="download-button" onClick={download} disabled={!regions}><Download/> เก็บผลงานของหนู</Button><small className="download-note">ดาวน์โหลดเป็นรูปภาพได้เลย</small></aside></div>
 <div className="bottom-strip"><div><span className="mini-step">3</span><p>แตะเติมสี <ChevronRight size={14}/> แล้วปล่อยจินตนาการให้โลดแล่น</p></div><span role="status" aria-live="polite"><Sparkles size={16}/>{notice}</span></div><footer><span><Palette size={15}/> แต้มสี · ความสุขเล็ก ๆ ในทุกสี</span><span>สำหรับศิลปินตัวน้อยวัย 3–6 ปี <span className="footer-dot">•</span> ผลงานเก็บไว้ในเครื่องนี้</span></footer></main>
 <Dialog open={help||resetOpen} onOpenChange={open=>{if(!open){setHelp(false);setResetOpen(false);}}}><DialogContent className="modal" showCloseButton={false}><Button variant="ghost" className="modal-close" aria-label="ปิด" onClick={()=>{setHelp(false);setResetOpen(false);}}><X/></Button>{help?<><span className="modal-icon"><Palette size={32}/></span><DialogTitle id="dialog-title">มาเล่นด้วยกัน!</DialogTitle><DialogDescription>1. เลือกรูปที่หนูชอบ<br/>2. แตะเลือกสีจากจานสี<br/>3. แตะช่องในรูปเพื่อเติมสี</DialogDescription><p className="modal-tip">เปลี่ยนสีได้ทุกเมื่อ ใช้ยางลบหรือย้อนกลับได้เลย<br/>ใช้แป้นพิมพ์: Tab เลือกเครื่องมือ ลูกศรเลือกช่องในรูป และ Enter เติมสี</p><Button className="download-button" onClick={()=>setHelp(false)}>เข้าใจแล้ว ไปเติมสีกัน <ChevronRight/></Button></>:<><span className="modal-icon"><RotateCcw size={32}/></span><DialogTitle id="dialog-title">เริ่มรูปนี้ใหม่ไหม?</DialogTitle><DialogDescription>สีในรูปนี้จะถูกล้างออก<br/>ถ้าเปลี่ยนใจ ยังใช้ปุ่มย้อนกลับได้</DialogDescription><Button className="download-button" onClick={reset}>เริ่มใหม่เลย</Button><Button variant="ghost" className="cancel-button" onClick={()=>setResetOpen(false)}>เติมสีต่อก่อน</Button></>}</DialogContent></Dialog>
 </div>;
}

